branches:
    only:
    - master
    - staging
    - trying
    - /^release\/.*$/ # release branches
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

language: julia

os:
    - linux
    # - osx

julia:
    - "1.2"
    - nightly

matrix:
    allow_failures:
        - julia: nightly
        - os: osx
    fast_finish: true

notifications:
    email: false

script: julia --inline=no -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
